## **CSGO PROJECT:-**

**Counter-Strike (CS)** is a popular series of tactical first-person shooter (FPS) video games that have been enjoyed by gamers worldwide for many years. The series originated as a modification for the popular game Half-Life and quickly gained its own dedicated following. Here's an overview of Counter-Strike:

**Gameplay Overview:**

Counter-Strike is primarily a multiplayer game where two teams, the Counter-Terrorists (CTs) and the Terrorists (Ts), compete against each other.

The objective of each round varies based on the game mode, but the primary goals include:

**Counter-Terrorists:** Prevent the Terrorists from achieving their objectives, such as defusing a bomb or rescuing hostages.

**Terrorists:** Achieve their objectives, which may include planting a bomb at a designated site or holding hostages.
Rounds are relatively short, typically lasting a few minutes, and players have only one life per round. When a player is eliminated, they must wait until the next round to respawn.

**Key Features:**

**Weapons:** Players can purchase and use a wide variety of firearms, grenades, and equipment. The choice of weaponry is an essential strategic element in the game.

**Economy:** Players earn in-game money based on their performance in the previous rounds. Money is used to buy weapons and equipment for the next round.

**Maps:** Counter-Strike features a range of maps, each with its own layout and objectives. Popular maps include Dust II, Mirage, Inferno, and more.

**Teamwork:** Successful gameplay in Counter-Strike heavily relies on teamwork, communication, and strategy. Players often coordinate their actions with their teammates to achieve objectives.

**Competitive Play:** Counter-Strike is well-known for its competitive scene, with professional esports tournaments held worldwide.

**Popular Game Modes:**

**Bomb Defusal (de_):** In this mode, Terrorists attempt to plant a bomb at one of the designated bomb sites, while Counter-Terrorists aim to prevent the bomb from being planted or defuse it if it's planted.

**Hostage Rescue (cs_):** In hostage rescue mode, Counter-Terrorists must rescue hostages held by the Terrorists, while the Terrorists aim to prevent the rescues.

**Arms Race:** A fast-paced mode where players cycle through a series of weapons, aiming to be the first to get a kill with each weapon.

**Deathmatch:** A mode where players respawn quickly and aim to get as many kills as possible within a set time limit.

**Wingman:** A 2v2 competitive mode with smaller maps and shorter rounds.

Counter-Strike has evolved over the years with different versions, including Counter-Strike 1.6, Counter-Strike: Source, and Counter-Strike: Global Offensive (CS:GO), which is the most recent and widely played installment as of my last knowledge update in September 2021.

CS:GO is known for its competitive gameplay, professional esports scene, and ongoing updates that have kept the game relevant and enjoyable for players worldwide. It remains a cornerstone of the first-person shooter genre.



## **READING OF DATASET:-**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving csgo_round_snapshots.csv to csgo_round_snapshots.csv


## **Importing Libnraries:-**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

## **ANALYSING EDA PROCESS:-**

In [ ]:
df = pd.read_csv('csgo_round_snapshots.csv')
df.head()

,time_left,ct_score,t_score,map,bomb_planted,ct_health,t_health,ct_armor,t_armor,ct_money,t_money,ct_helmets,t_helmets,ct_defuse_kits,ct_players_alive,t_players_alive,ct_weapon_ak47,t_weapon_ak47,ct_weapon_aug,t_weapon_aug,ct_weapon_awp,t_weapon_awp,ct_weapon_bizon,t_weapon_bizon,ct_weapon_cz75auto,t_weapon_cz75auto,ct_weapon_elite,t_weapon_elite,ct_weapon_famas,t_weapon_famas,ct_weapon_g3sg1,t_weapon_g3sg1,ct_weapon_galilar,t_weapon_galilar,ct_weapon_glock,t_weapon_glock,ct_weapon_m249,t_weapon_m249,ct_weapon_m4a1s,t_weapon_m4a1s,...,t_weapon_p90,ct_weapon_r8revolver,t_weapon_r8revolver,ct_weapon_sawedoff,t_weapon_sawedoff,ct_weapon_scar20,t_weapon_scar20,ct_weapon_sg553,t_weapon_sg553,ct_weapon_ssg08,t_weapon_ssg08,ct_weapon_ump45,t_weapon_ump45,ct_weapon_xm1014,t_weapon_xm1014,ct_weapon_deagle,t_weapon_deagle,ct_weapon_fiveseven,t_weapon_fiveseven,ct_weapon_usps,t_weapon_usps,ct_weapon_p250,t_weapon_p250,ct_weapon_p2000,t_weapon_p2000,ct_weapon_tec9,t_weapon_tec9,ct_grenade_hegrenade,t_grenade_hegrenade,ct_grenade_flashbang,t_grenade_flashbang,ct_grenade_smokegrenade,t_grenade_smokegrenade,ct_grenade_incendiarygrenade,t_grenade_incendiarygrenade,ct_grenade_molotovgrenade,t_grenade_molotovgrenade,ct_grenade_decoygrenade,t_grenade_decoygrenade,round_winner
0,175.00,0.0,0.0,de_dust2,False,500.0,500.0,0.0,0.0,4000.0,4000.0,0.0,0.0,0.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
1,156.03,0.0,0.0,de_dust2,False,500.0,500.0,400.0,300.0,600.0,650.0,0.0,0.0,1.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
2,96.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,500.0,0.0,0.0,1.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
3,76.03,0.0,0.0,de_dust2,False,391.0,400.0,294.0,200.0,750.0,500.0,0.0,0.0,1.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT
4,174.97,1.0,0.0,de_dust2,False,500.0,500.0,192.0,0.0,18350.0,10750.0,0.0,0.0,1.0,5.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,CT


In [ ]:
df.shape # checking of shape of the dataframe

(122410, 97)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 117448 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   time_left                     117448 non-null  float64
 1   ct_score                      117448 non-null  float64
 2   t_score                       117448 non-null  float64
 3   map                           117448 non-null  object 
 4   bomb_planted                  117448 non-null  bool   
 5   ct_health                     117448 non-null  float64
 6   t_health                      117448 non-null  float64
 7   ct_armor                      117448 non-null  float64
 8   t_armor                       117448 non-null  float64
 9   ct_money                      117448 non-null  float64
 10  t_money                       117448 non-null  float64
 11  ct_helmets                    117448 non-null  float64
 12  t_helmets                     117448 non-null  fl

In [ ]:
df.isnull().sum().sum()# checking for null values

np.int64(0)

In [ ]:
df.duplicated().sum() # checking for duplicated values

np.int64(4962)

In [ ]:
# Eliminating duplicate values:-
df.drop_duplicates(inplace=True)

In [ ]:
df.duplicated().sum()# rechaking

np.int64(0)

In [ ]:
object_columns=df.select_dtypes('object').columns # checking for non numeric columns
object_columns

Index(['map', 'round_winner'], dtype='object')

In [ ]:
le=LabelEncoder() # transforming of data-type
for i in object_columns:
  df[i]=le.fit_transform(df[i])

In [ ]:
df['bomb_planted']=le.fit_transform(df['bomb_planted'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 117448 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   time_left                     117448 non-null  float64
 1   ct_score                      117448 non-null  float64
 2   t_score                       117448 non-null  float64
 3   map                           117448 non-null  int64  
 4   bomb_planted                  117448 non-null  int64  
 5   ct_health                     117448 non-null  float64
 6   t_health                      117448 non-null  float64
 7   ct_armor                      117448 non-null  float64
 8   t_armor                       117448 non-null  float64
 9   ct_money                      117448 non-null  float64
 10  t_money                       117448 non-null  float64
 11  ct_helmets                    117448 non-null  float64
 12  t_helmets                     117448 non-null  fl

# **ML PROCESS:-**

In [ ]:
x=df.drop('round_winner',axis=1)
y=df['round_winner']

In [ ]:
y.value_counts()# balanced dataset

,count
round_winner,
1,59941
0,57507


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=52) # splitting of data elements

In [ ]:
sc=StandardScaler() # standard scaling
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [ ]:
x_train

array([[-0.19780327, -1.41328349, -1.41743107, ..., -0.82920241,
        -0.16378212, -0.15403986],
       [-1.04247343,  0.46284855,  1.69030656, ...,  0.96358137,
        -0.16378212, -0.15403986],
       [-1.37992836, -1.41328349, -1.41743107, ..., -0.82920241,
        -0.16378212, -0.15403986],
       ...,
       [-1.27457932,  0.25438943, -1.21024856, ...,  0.36598678,
        -0.16378212, -0.15403986],
       [-0.08926184, -0.37098792, -0.17433602, ...,  0.96358137,
        -0.16378212, -0.15403986],
       [ 1.50599672, -0.1625288 ,  1.06875904, ..., -0.82920241,
        -0.16378212, -0.15403986]])

In [ ]:
x_test

array([[-0.74745857, -0.1625288 , -0.17433602, ...,  0.36598678,
        -0.16378212, -0.15403986],
       [-1.33861501,  0.67130766,  0.65439402, ..., -0.82920241,
        -0.16378212, -0.15403986],
       [-1.17467614,  0.46284855, -0.58870103, ..., -0.23160782,
        -0.16378212, -0.15403986],
       ...,
       [-1.12303445, -1.41328349, -1.41743107, ..., -0.82920241,
        -0.16378212, -0.15403986],
       [ 0.00406877, -1.41328349, -1.41743107, ..., -0.23160782,
        -0.16378212, -0.15403986],
       [-1.19307935, -0.37098792, -0.17433602, ..., -0.82920241,
        -0.16378212, -0.15403986]])

## **BEST COLUMNS SELECTION THROUGH LDA PROCESS:-**

In [ ]:
lda=LinearDiscriminantAnalysis() # LDA process
lda.fit(x_train,y_train)

LinearDiscriminantAnalysis()

In [ ]:
lda.transform(x_test)

array([[ 0.43025877],
       [ 2.37148253],
       [ 3.73328874],
       ...,
       [-1.00743851],
       [-0.1957808 ],
       [ 1.49747098]])

In [ ]:
lda.coef_

array([[ 1.40229762e-01, -2.03561152e-02,  1.62597031e-02,
        -8.82766545e-02,  2.48168963e-01, -4.51910245e-01,
         2.86682063e-01, -6.19566493e-01,  6.37638848e-01,
        -2.13826060e-01,  1.59227933e-01,  2.66398067e-02,
         9.88712072e-02, -3.59015920e-02, -2.17938520e-01,
         4.02671805e-01, -1.86637628e-01,  5.95572469e-01,
        -1.97675403e-01,  3.63095491e-02, -3.07118943e-01,
         2.43902317e-01, -1.65065874e-16, -6.17629158e-03,
         2.41921016e-02, -2.27134069e-03, -8.75422268e-03,
         2.20497971e-02, -1.31495398e-01,  4.35067262e-02,
         2.46592719e-16,  1.74480931e-02, -5.14939233e-02,
         1.34221862e-01,  2.13817802e-02, -1.49316136e-01,
         1.15264877e-02, -4.02734434e-16, -8.72828837e-02,
         4.51955814e-02, -4.60628135e-01,  1.06776907e-01,
        -1.25584749e-02,  1.06301679e-01, -1.58519679e-02,
         7.36342004e-03, -1.80133410e-02,  3.29451060e-02,
         6.55030800e-03, -1.01388673e-02, -1.10537081e-0

In [ ]:
new_lda=np.exp(np.abs(lda.coef_)) # converting into positive values
new_lda

array([[1.15053812, 1.02056471, 1.01639261, 1.09229027, 1.28167647,
        1.57131091, 1.33200065, 1.85812236, 1.89200828, 1.23840723,
        1.17260519, 1.02699782, 1.10392411, 1.03655384, 1.24351061,
        1.49581589, 1.20519048, 1.81406915, 1.21856679, 1.03697679,
        1.35950266, 1.27621966, 1.        , 1.0061954 , 1.0244871 ,
        1.00227392, 1.00879265, 1.02229469, 1.14053266, 1.04446702,
        1.        , 1.0176012 , 1.05284279, 1.14364652, 1.02161201,
        1.16103998, 1.01159317, 1.        , 1.09120532, 1.04623246,
        1.58506931, 1.11268599, 1.01263766, 1.11215734, 1.01597828,
        1.0073906 , 1.01817656, 1.03349381, 1.00657181, 1.01019044,
        1.11687776, 1.04029974, 1.        , 1.        , 1.01530723,
        1.01621272, 1.01995965, 1.01807367, 1.        , 1.00855057,
        1.        , 1.02142052, 1.00484646, 1.01236758, 1.22899015,
        1.72160533, 1.09215062, 1.0264597 , 1.04957771, 1.08935185,
        1.01998341, 1.00821244, 1.05809667, 1.00

In [ ]:
strength=new_lda.flatten()
strength

array([1.15053812, 1.02056471, 1.01639261, 1.09229027, 1.28167647,
       1.57131091, 1.33200065, 1.85812236, 1.89200828, 1.23840723,
       1.17260519, 1.02699782, 1.10392411, 1.03655384, 1.24351061,
       1.49581589, 1.20519048, 1.81406915, 1.21856679, 1.03697679,
       1.35950266, 1.27621966, 1.        , 1.0061954 , 1.0244871 ,
       1.00227392, 1.00879265, 1.02229469, 1.14053266, 1.04446702,
       1.        , 1.0176012 , 1.05284279, 1.14364652, 1.02161201,
       1.16103998, 1.01159317, 1.        , 1.09120532, 1.04623246,
       1.58506931, 1.11268599, 1.01263766, 1.11215734, 1.01597828,
       1.0073906 , 1.01817656, 1.03349381, 1.00657181, 1.01019044,
       1.11687776, 1.04029974, 1.        , 1.        , 1.01530723,
       1.01621272, 1.01995965, 1.01807367, 1.        , 1.00855057,
       1.        , 1.02142052, 1.00484646, 1.01236758, 1.22899015,
       1.72160533, 1.09215062, 1.0264597 , 1.04957771, 1.08935185,
       1.01998341, 1.00821244, 1.05809667, 1.00255843, 1.04899

In [ ]:
new_df=pd.DataFrame({'columns':x.columns,'strength':strength}) # creating dataframe
new_df

,columns,strength
0,time_left,1.150538
1,ct_score,1.020565
2,t_score,1.016393
3,map,1.092290
4,bomb_planted,1.281676
...,...,...
91,t_grenade_incendiarygrenade,1.012464
92,ct_grenade_molotovgrenade,1.001905
93,t_grenade_molotovgrenade,1.096875
94,ct_grenade_decoygrenade,1.003879


In [36]:
new_cols=new_df.nlargest(20,'strength')['columns'] # selecting 20 best columns
new_cols

,columns
8,t_armor
7,ct_armor
17,t_weapon_ak47
65,t_weapon_sg553
40,ct_weapon_m4a4
5,ct_health
15,t_players_alive
20,ct_weapon_awp
6,t_health
4,bomb_planted


In [37]:
x_train_new=x_train[:,new_cols.index]
x_test_new=x_test[:,new_cols.index]

In [39]:
x_train_new.shape

(93958, 20)

In [40]:
x_test_new.shape

(23490, 20)

## **CLASSIFICATION MODEL BUILDING:-**

In [41]:
model1=LogisticRegression()
model2=DecisionTreeClassifier()
model3=RandomForestClassifier()

## **Prediction Task:-**

# Logistic Regression:-

In [42]:
model1.fit(x_train_new,y_train)
y_pred=model1.predict(x_test_new)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[8729 2748]
 [2988 9025]]
0.7558109833971903


# Decision Tree classifier:-

In [43]:
model2.fit(x_train_new,y_train)
y_pred=model2.predict(x_test_new)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[9307 2170]
 [2224 9789]]
0.8129416773094934


# Random Foresrt Classifier:-

In [44]:
model3.fit(x_train_new,y_train)
y_pred=model3.predict(x_test_new)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[ 9892  1585]
 [ 1779 10234]]
0.8567901234567902


## RAMDOM FOREST CLASSIFIER FITS ON THE DATA WELL.THIS EXPERIMENT PROVES THAT FOR LARGE COMPLEX DATA RANDOM FOREST,DECISION TREE THESE COMPLEX MODELS WORKS WELL.